<?php

/**
 * Implements hook_menu().
 */

function islandora_critical_edition_menu() {
  $items['islandora/object/%islandora_object/manage/crited'] = array(
    'title' => 'Critical Editions',
    'page callback' => 'islandora_critical_edition_management',
    'page arguments' => array(2),
    'type' => MENU_LOCAL_TASK,
    'access callback' => 'islandora_critical_edition_access',
    'access arguments' => array(2),
    'file' => 'includes/critical_edition.inc'
  );

  $items['islandora/cwrcwriter/setup/%islandora_object'] = array(
    'title' => 'Cwrcwriter Setup',
    'page callback' => 'islandora_critical_edition_setup',
    'page arguments' => array(3),
    'type' => MENU_CALLBACK,
    'access callback' => 'islandora_critical_edition_access',
    'access arguments' => array(3),
    'file' => 'includes/critical_edition_callbacks.inc'
  );
  $items['islandora/cwrcwriter/get_data/%islandora_object'] = array(
    'title' => 'Get Data',
    'page callback' => 'islandora_critical_edition_getdata',
    'page arguments' => array(3),
    'type' => MENU_CALLBACK,
    'access callback' => 'islandora_critical_edition_access',
    'access arguments' => array(3),
    'file' => 'includes/critical_edition_callbacks.inc'
  );
  
  $items['islandora/cwrcwriter/save_data/%islandora_object'] = array(
    'title' => 'Save Data',
    'page callback' => 'islandora_critical_edition_savedata',
    'page arguments' => array(3),
    'type' => MENU_CALLBACK,
    'access callback' => 'islandora_critical_edition_access',
    'access arguments' => array(3),
    'file' => 'includes/critical_edition_callbacks.inc'
  );
  $items['islandora/cwrcwriter/setup_shared/%islandora_object'] = array(
    'title' => 'Shared Canvas Setup',
    'page callback' => 'islandora_critical_edition_canvas_setup',
    'page arguments' => array(3),
    'type' => MENU_CALLBACK,
    'access callback' => 'islandora_critical_edition_access',
    'access arguments' => array(3),
    'file' => 'includes/critical_edition_callbacks.inc'
  );

  return $items;
}

//  todo - make permissions make sense
function islandora_critical_edition_access($object = null) {
  if (!isset($object)) {
    return FALSE;
  }
  $models = $object->models;
  $is_book = in_array('islandora:bookCModel', $object->models);
  $is_critical_edition = in_array('islandora:criticalEditionCModel', $object->models);
  $is_system = in_array('fedora-system:FedoraObject-3.0', $object->models);  //need to go, not sure where its coming from
  return ($is_book || $is_critical_edition || $is_system) && islandora_object_access_callback(FEDORA_VIEW_OBJECTS, $object);
}

/**
 * Implements hook_permission().
 * Additional permissions to come
 */

function islandora_critical_edition_permission() {
  return array(
    'use CWRC' => array(
      'title' => t('Use CWRCWriter'),
      'description' => t('Access CWRCWriter.'),
    ),
    'edit CWRC' => array(
      'title' => t('Edit with CWRCWriter'),
      'description' => t('Edit and save content within CWRCWriter to objects in the repository. Note: Fedora XACML security policies may override this position.'),
    ),
  );
}

/**
 * Implements hook_theme().
 */
function islandora_critical_edition_theme($existing, $type, $theme, $path) {
  return array(
    'islandora_critical_edition' => array(
      'file' => 'theme/theme.inc',
      'template' => 'theme/islandora-crited',
      'pattern' => 'islandora_critical_edition__',
      'variables' => array('islandora_object' => NULL),
    )
  );
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_critical_edition_islandora_criticalEditionCModel_islandora_view_object($object, $page_number, $page_size) {
  $output = theme('islandora_critical_edition', array('islandora_object' => $object));
  return array('' => $output);
}



/**
 * Implements hook_islandora_required_objects().
 */
function islandora_critical_edition_islandora_required_objects(IslandoraTuque $connection) {
  $module_path = drupal_get_path('module', 'islandora_critical_edition');
  $datastreams_path = "$module_path/data/datastreams";

  // Page Content Model.
  $critical_edition_page_content_model = $connection->repository->constructObject('islandora:criticalEditionCModelPage');
  $critical_edition_page_content_model->owner = 'fedoraAdmin';
  $critical_edition_page_content_model->label = 'Islandora Critical Edition Page Content Model';
  $critical_edition_page_content_model->models = 'fedora-system:ContentModel-3.0';
  // DS-COMPOSITE-MODEL Datastream.
  $datastream = $critical_edition_page_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'M');
  $datastream->label = 'DS-COMPOSITE-MODEL';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$datastreams_path/islandora_crtitical_edition_pageCModel_ds_composite_model.xml", FALSE);
  $critical_edition_page_content_model->ingestDatastream($datastream);
  // Ctitical Edition Content Model.
  $critical_edition_content_model = $connection->repository->constructObject('islandora:criticalEditionCModel');
  $critical_edition_content_model->owner = 'fedoraAdmin';
  $critical_edition_content_model->label = 'Islandora Critical Edition Content Model';
  $critical_edition_content_model->models = 'fedora-system:ContentModel-3.0';
  // DS-COMPOSITE-MODEL Datastream.
  $datastream = $critical_edition_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'M');
  $datastream->label = 'DS-COMPOSITE-MODEL';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$datastreams_path/islandora_criticalEditionCModel_ds_composite_model.xml", FALSE);
  $critical_edition_content_model->ingestDatastream($datastream);

  return array(
  'islandora_critical_edition' => array(
      'title' => 'Islandora critical editions',
      'objects' => array(
        $critical_edition_content_model,
        $critical_edition_page_content_model,
      )
    )
  );
}