<?php

function islandora_critical_edition_menu() {
  $items['islandora/object/%islandora_object/manage/crited'] = array(
    'title' => 'Critical Editions',
    'page callback' => 'islandora_critical_edition_management',
    'page arguments' => array(2),
    'type' => MENU_LOCAL_TASK,
    'access callback' => 'islandora_critical_edition_access',
    'access arguments' => array(2),
    'file' => 'includes/critical_edition.inc'
  );

  $items['islandora/cwrcwriter/setup/%islandora_object'] = array(
    'title' => 'Cwrcwriter Setup',
    'page callback' => 'islandora_critical_edition_setup',
    'page arguments' => array(3),
    'type' => MENU_CALLBACK,
    'access callback' => 'islandora_critical_edition_access',
    'access arguments' => array(3),
    'file' => 'includes/critical_edition_callbacks.inc'
  );
  $items['islandora/cwrcwriter/get_data/%islandora_object'] = array(
    'title' => 'Get Data',
    'page callback' => 'islandora_critical_edition_getdata',
    'page arguments' => array(3),
    'type' => MENU_CALLBACK,
    'access callback' => 'islandora_critical_edition_access',
    'access arguments' => array(3),
    'file' => 'includes/critical_edition_callbacks.inc'
  );
  
  $items['islandora/cwrcwriter/save_data/%islandora_object'] = array(
    'title' => 'Save Data',
    'page callback' => 'islandora_critical_edition_savedata',
    'page arguments' => array(3),
    'type' => MENU_CALLBACK,
    'access callback' => 'islandora_critical_edition_access',
    'access arguments' => array(3),
    'file' => 'includes/critical_edition_callbacks.inc'
  );
  $items['islandora/cwrcwriter/setup_shared/%islandora_object'] = array(
    'title' => 'Shared Canvas Setup',
    'page callback' => 'islandora_critical_edition_canvas_setup',
    'page arguments' => array(3),
    'type' => MENU_CALLBACK,
    'access callback' => 'islandora_critical_edition_access',
    'access arguments' => array(3),
    'file' => 'includes/critical_edition_callbacks.inc'
  );

  return $items;
}

//  todo - make permissions make sense
function islandora_critical_edition_access($object = null) {
  if (!isset($object)) {
    return FALSE;
  }
  $models = $object->models;
  $is_book = in_array('islandora:bookCModel', $object->models);
  $is_critical_edition = in_array('islandora:criticalEditionCModel', $object->models);
  $is_system = in_array('fedora-system:FedoraObject-3.0', $object->models);  //need to go
  return ($is_book || $is_critical_edition || $is_system) && islandora_object_access_callback(FEDORA_VIEW_OBJECTS, $object);
}

/**
 * Implements hook_theme().
 */
function islandora_critical_edition_theme($existing, $type, $theme, $path) {
  return array(
    'islandora_critical_edition' => array(
      'file' => 'theme/theme.inc',
      'template' => 'theme/islandora-crited',
      'pattern' => 'islandora_critical_edition__',
      'variables' => array('islandora_object' => NULL),
    )
  );
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_critical_edition_islandora_criticalEditionCModel_islandora_view_object($object, $page_number, $page_size) {
  $output = theme('islandora_critical_edition', array('islandora_object' => $object));
  return array('' => $output);
}